config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  resources :articles
  resources :films

  namespace :api do
    resources :articles, only: [:index, :show]
    resources :films, only: [:index, :show]
  end
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  mount_uploader :poster, PosterUploader
  mount_uploaders :photos, PhotoUploader

  field :title, type: String
  field :content, type: String
  field :date, type: Date, default: DateTime.now.strftime("%d.%m.%Y")
  field :photos, type: Array, default: []
end

app/models/film.rb
class Film
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::GridFsHelper

  mount_uploader :poster, PosterUploader

  field :title, type: String
  field :year, type: Integer
  field :trailer, type: String
  field :director, type: String
  field :description, type: String
  field :actors, type: Array
  field :genres, type: Array
  field :online_cinemas, type: Array
  field :type_film, type: String, default: 'Полнометражный фильм'

  validates :year, presence: true, numericality: { only_integer: true }, length: { is: 4 }

  before_destroy :delete_image_directory
  before_save :process_genres
  before_save :process_actors
  before_save :process_online_cinemas

  private

  def delete_image_directory
    dir_image_path = poster.current_path

    if File.directory?(File.dirname(dir_image_path))
      FileUtils.rm_rf(File.dirname(dir_image_path))
      dir_image_path
    end
  end

  def process_genres
    self.genres = genres.first.split(',').map(&:strip)
  end

  def process_online_cinemas
    self.online_cinemas = online_cinemas.first.split(',').map(&:strip)
  end

  def process_actors
    self.actors = actors.first.split(',').map(&:strip)
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :role, type: String, default: "user"
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def admin?
    role == 'admin'
  end

  include Mongoid::Timestamps
end

app/controllers/api/articles_controller.rb
module Api
  class ArticlesController < ApplicationController
    def index
      @articles = Article.all
      render json: @articles
    end

    def show
      @article = Article.find(params[:id])
      render json: @article
    end
  end
end

app/controllers/api/films_controller.rb
module Api
  class FilmsController < ApplicationController
    def index
      @films = Film.all
      render json: @films
    end

    def show
      @film = Film.find(params[:id])
      render json: @film
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end

  private

  def user_not_authorized
    flash[:error] = "Вы не уполномочены выполнять это действие."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @articles = policy_scope(Article)
  end

  def show
    authorize @article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @article
  end

  def update
    authorize @article

    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @article
    @article.destroy

    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    existing_photos = @article&.photos || []

    params.require(:article).permit(:title, :content, :poster, photos: []).tap do |whitelisted|
      whitelisted[:photos] = existing_photos + whitelisted[:photos]
    end
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  before_action :load_film_types, only: [:new, :edit, :create]
  before_action :authenticate_user!

  def index
    @films = policy_scope(Film)
  end

  def show
    authorize @film
  end

  def new
    @film = Film.new
  end

  def edit
    authorize @film
  end

  def create
    @film = Film.new(film_params)

    if @film.save
      redirect_to @film, notice: 'Film was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @film

    if @film.update(film_params)
      redirect_to @film, notice: 'Film was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @film
    @film.destroy

    redirect_to films_url, notice: 'Film was successfully destroyed.'
  end

  private

  def set_film
    @film = Film.find(params[:id])
  end

  def film_params
    params.require(:film).permit(:title, :poster, :year, :trailer, :director, :description, :type_film, online_cinemas: [], genres: [], actors: [])
  end

  def load_film_types
    @film_types = YAML.safe_load(File.read(Rails.root.join('config', 'film_types.yml'))).presence || []
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
  end

  def update
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  before_action :authenticate_user!

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/helpers/api/articles_helper.rb
module Api::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true, html: { multipart: true }) do |form| %>
  <div class="max-w-md mx-auto mt-8 space-y-6">
    <div class="mb-4">
      <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :title, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <% if article.try(:poster).present? %>
      <%= image_tag article.poster.url, class: 'w-1/2' %>
    <% end %>

    <div class="mb-4">
      <%= form.label :poster, class: "block text-sm font-medium text-gray-700" %>
      <%= form.file_field :poster, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="field">
      <%= form.label :photos, 'Загрузить фото' %>
      <%= form.file_field :photos, multiple: true %>
    </div>

    <div class="mb-4">
      <%= form.label :content, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_area :content, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="flex items-center justify-between">
      <%= form.submit "Создать", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-5xl font-bold mb-4">Редактирование: <%= @article.title %></h1>

<%= render 'form', article: @article %>

<%= link_to 'Назад', articles_path %>

app/views/articles/index.html.erb
<h1 class="text-5xl font-bold mb-4">Статьи</h1>

<% if @articles.count.zero? %>
  <p>Записи отсутствуют</p>
<% else %>
  <table class="min-w-full">
    <thead>
    <tr>
      <th class="py-2">Название</th>
      <th class="py-2"></th>
    </tr>
    </thead>
    <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td class="py-2"><%= link_to article.title, article %></td>
        <td class="py-2">
          <%= link_to "Редактировать", edit_article_path(article), class: "text-blue-500 hover:text-blue-700 font-semibold mr-2" %>
          <%= link_to "Удалить", article, data: { confirm: "Вы уверены?", "turbo-method": :delete }, class: "text-red-500 hover:text-red-700 font-semibold" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to "Добавить статью", new_article_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-4 inline-block" %>

<%= link_to 'На главную', root_path, class: 'block mt-5' %>

app/views/articles/new.html.erb
<h1 class="text-5xl font-bold mb-4">Добавить статью</h1>

<%= render 'form', article: @article %>

<%= link_to 'Отмена', articles_path, class: "text-blue-500 hover:text-blue-700 font-semibold mt-4 inline-block" %>

app/views/articles/show.html.erb
<h1 class="text-5xl font-bold mb-4"><%= @article.title %></h1>

<div class="mb-8">
  <% if @article.poster.present? %>
    <h2>Постер</h2>
    <div class="photo-gallery">
      <%= image_tag @article.poster.url, class: 'w-1/2 gallery-image' %>
    </div>
  <% else %>
    <p>Постер не загружен</p>
  <% end %>
</div>

<% if @article.photos.present? %>
  <h2>Фото</h2>
  <div class="photo-gallery">
    <% @article.photos.each do |photo| %>
      <%= image_tag photo.url, alt: 'Фотографии', class: 'gallery-image' %>
    <% end %>
  </div>
<% end %>

<p class="mb-8"><strong>Содержание:</strong> <%= @article.content %></p>

<div class="mt-8">
  <%= link_to 'Редактировать', edit_article_path(@article), class: 'border p-2' %>
  <%= link_to 'Удалить', @article, class: 'display: inline', data: { "turbo-method": :delete } %> |
  <%= link_to 'Назад', articles_path %>
</div>

app/views/films/_form.html.erb
<%= form_with(model: film, local: true, html: { multipart: true }) do |form| %>
  <div class="max-w-md mx-auto mt-8 space-y-6">
    <div class="mb-4">
      <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :title, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <% if film.try(:poster).present? %>
      <%= image_tag film.poster.url, class: 'w-1/2' %>
    <% end %>

    <div class="mb-4">
      <%= form.label :poster, class: "block text-sm font-medium text-gray-700" %>
      <%= form.file_field :poster, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :year, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :year, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300", pattern: '\d{4}' %>
    </div>

    <div class="mb-4">
      <%= form.label :type_film, class: "block text-sm font-medium text-gray-700" %>
      <%= form.select :type_film, @film_types, { prompt: "Выберите тип фильма" }, { class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" } %>
    </div>

    <div class="mb-4">
      <%= form.label :trailer, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :trailer, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :director, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :director, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :description, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_area :description, class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :genres, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :genres, name: 'film[genres][]', value: film.try(:genres).present? ? film.genres.join(', ') : '', class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :actors, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :actors, name: 'film[actors][]', value: film.try(:actors).present? ? film.actors.join(', ') : '', class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="mb-4">
      <%= form.label :online_cinemas, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :online_cinemas, name: 'film[online_cinemas][]', value: film.try(:online_cinemas).present? ? film.online_cinemas.join(', ') : '', class: "mt-1 p-2 border rounded-md w-full focus:outline-none focus:ring focus:border-blue-300" %>
    </div>

    <div class="flex items-center justify-between">
      <%= form.submit "Создать", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1 class="text-5xl font-bold mb-4">Редактирование: <%= @film.title %></h1>

<%= render 'form', film: @film %>

<%= link_to 'Назад', films_path %>

app/views/films/index.html.erb
<h1 class="text-5xl font-bold mb-4">Фильмы</h1>

<% if @films.count.zero? %>
  <p>Фильмы отсутствуют</p>
<% else %>
  <table class="min-w-full">
    <thead>
    <tr>
      <th class="py-2">Название</th>
      <th class="py-2"></th>
    </tr>
    </thead>
    <tbody>
    <% @films.each do |film| %>
      <tr>
        <td class="py-2"><%= link_to film.title, film %></td>
        <td class="py-2">
          <%= link_to "Редактировать", edit_film_path(film), class: "text-blue-500 hover:text-blue-700 font-semibold mr-2" %>
          <%= link_to "Удалить", film, data: { confirm: "Вы уверены?", "turbo-method": :delete }, class: "text-red-500 hover:text-red-700 font-semibold" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<% if current_user %>
  <%= link_to "Добавить фильм", new_film_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-4 inline-block" %>
<% end %>

<%= link_to 'На главную', root_path, class: 'block mt-5' %>

app/views/films/new.html.erb
<h1 class="text-5xl font-bold mb-4">Новый фильм</h1>

<%= render 'form', film: @film %>

<%= link_to 'Отмена', films_path, class: "text-blue-500 hover:text-blue-700 font-semibold mt-4 inline-block" %>

app/views/films/show.html.erb
<h1 class="text-5xl font-bold mb-4"><%= @film.title %></h1>

<div class="mb-8">
  <% if @film.poster.present? %>
    <div class="photo-gallery">
      <%= image_tag @film.poster.url, class: 'w-1/2' %>
    </div>
  <% else %>
    <p>Постер не загружен</p>
  <% end %>
</div>

<p><strong>Год:</strong> <%= @film.year %></p>
<p><strong>Формат фильма:</strong> <%= @film.type_film %></p>
<p><strong>Трейлер:</strong> <%= link_to @film.trailer, @film.trailer %></p>
<p><strong>Режисёр:</strong> <%= @film.director %></p>
<p><strong>Описание:</strong> <%= @film.description %></p>
<p><strong>Жанр:</strong> <%= @film.genres.present? ? @film.genres.join(', ') : '' %></p>
<p><strong>Актёры:</strong> <%= @film.actors.present? ? @film.actors.join(', ') : '' %></p>

<% if @film.online_cinemas.present? %>
  <p><strong>Онлайн кинотеатры:</strong></p>
  <ul>
    <% @film.online_cinemas.each do |cinema| %>
      <li><%= cinema %></li>
    <% end %>
  </ul>
<% end %>

<div class="mt-8">
  <%= link_to 'Редактировать', edit_film_path(@film), class: 'border p-2' %>
  <%= link_to 'Удалить', @film, class: 'display: inline', data: { "turbo-method": :delete } %> |
  <%= link_to 'Назад', films_path %>
</div>

app/views/home/index.html.erb
<h1 class="text-5xl font-bold mb-4">VikingFilm | Админ-панель</h1>

<% if current_user %>
<p class="text-gray-600 mb-8">Добро пожаловать <%= current_user.email %></p>

  <%= link_to 'Фильмы', films_path, class: 'block' %>
  <%= link_to 'Статьи', articles_path, class: 'block' %>
<% end %>

<div class="mt-8">
  <%= render 'devise/shared/links' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Viking</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<div class="container mx-auto mt-4">
  <%= yield %>
</div>
</body>
</html>